version: '3.1'

services:
  php:
    container_name: php8.2-fpm
    image: woosungchoi/fpm-alpine:8.2-arm64
    restart: always
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./data:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - traefik-public            
  web:
    depends_on:
      - php
    container_name: nginx-1.22
    image: woosungchoi/docker-nginx-brotli:arm64
    restart: always
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./data:/var/www/html
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/log/nginx:/var/log/nginx
    expose:
      - 80
    labels:
      - traefik.enable=true
      # Docker내 어플리케이션 서버가 다르다면 포트변경 필요
      - traefik.http.services.nginx.loadbalancer.server.port=80
      - traefik.http.routers.nginx-http.entrypoints=http
      # 자신의 Subdomain으로 변경필요
      - traefik.http.routers.nginx-http.rule=Host(`word.ccbb.kr`)
      - traefik.docker.network=traefik-public
      - traefik.http.routers.nginx-https.entrypoints=https
      # 자신의 Subdomain으로 변경필요
      - traefik.http.routers.nginx-https.rule=Host(`word.ccbb.kr`)
      - traefik.http.routers.nginx-https.tls=true
      - traefik.http.routers.nginx-https.tls.certresolver=le
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.routers.nginx-http.middlewares=https-redirect

    networks:
      - traefik-public      
  db:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    expose:
      - 3306
    environment:
      - TZ=Asia/Seoul
      - MARIADB_ROOT_PASSWORD=example
      - MARIADB_USER=ccbbkr
      - MARIADB_PASSWORD=example
      - MARIADB_DATABASE=wordpress
    volumes:
      - ./config/db/init:/docker-entrypoint-initdb.d
      - ./data/db:/var/lib/mysql
      - ./config/db/my.cnf:/etc/mysql/my.cnf 
    networks:
      - traefik-public
  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./data/dataredis:/data
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru --appendonly yes
    networks:
      - traefik-public

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    # ports:
    #   - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_ARBITRARY=1
    depends_on:
      - db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./php/php.ini:/usr/local/etc/php/php.ini     
    expose:
      - "80"
    labels:
      - traefik.enable=true
      # Docker내 어플리케이션 서버가 다르다면 포트변경 필요
      - traefik.http.services.phpmyadmin.loadbalancer.server.port=80
      - traefik.http.routers.phpmyadmin-http.entrypoints=http
      # 자신의 Subdomain으로 변경필요
      - traefik.http.routers.phpmyadmin-http.rule=Host(`pma.ccbb.kr`)
      - traefik.docker.network=traefik-public
      - traefik.http.routers.phpmyadmin-https.entrypoints=https
      # 자신의 Subdomain으로 변경필요
      - traefik.http.routers.phpmyadmin-https.rule=Host(`pma.ccbb.kr`)
      - traefik.http.routers.phpmyadmin-https.tls=true
      - traefik.http.routers.phpmyadmin-https.tls.certresolver=le
      - traefik.http.middlewares.phpmyadmin-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.phpmyadmin-redirect.redirectscheme.permanent=true
      - traefik.http.routers.phpmyadmin-http.middlewares=https-redirect
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
